apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: jonasandersen-admin
spec:
  selector:
    matchLabels:
      app: jonasandersen-admin
  replicas: 2
  template:
    metadata:
      labels:
        app: jonasandersen-admin
    spec:
      containers:
        - image: bjoggis/jonasandersen-admin:v80 # {"$imagepolicy": "flux-system:jonasandersen-admin"}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CONFIG_IMPORT
              value: 'optional:configserver:http://config-server-service.common.svc.cluster.local:8888'
            - name: loki.url
              value: 'http://five.tailscale.svc.cluster.local:3100/loki/api/v1/push'
          name: jonasandersen-admin
---
apiVersion: v1
kind: Service
metadata:
  name: jonasandersen-admin-service
  namespace: jonasandersen-admin
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: jonasandersen-admin