apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: jonasandersen-admin
spec:
  selector:
    matchLabels:
      app: jonasandersen-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: jonasandersen-admin
    spec:
      containers:
        - image: bjoggis/jonasandersen-admin:v79 # {"$imagepolicy": "flux-system:jonasandersen-admin"}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-profiles
                  key: spring_profiles_active
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
          name: jonasandersen-admin
