apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: admin
  namespace: jonasandersen-admin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "2"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
    spec:
      containers:
        - image: bjoggis/jonasandersen-admin:v69 # {"$imagepolicy": "flux-system:jonasandersen-admin"}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-profiles
                  key: spring_profiles_active
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
