apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: jonasandersen-admin
  namespace: flux-system
spec:
  image: bjoggis/jonasandersen-admin
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jonasandersen-admin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jonasandersen-admin
  filterTags:
    pattern: '.*v\d+(?!\S).*'
  policy:
    alphabetical:
      order: asc