apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: admin
  namespace: bjoggis-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
        autoscaling.knative.dev/window: "10m"
    spec:
      containers:
        - image: bjoggis/jonasandersen-admin:v0.0.11 # {"$imagepolicy": "flux-system:jonasandersen-admin"}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "--enable-preview"
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: security_username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: security_password
