apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: admin
  namespace: bjoggis-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
        autoscaling.knative.dev/window: "30m"
    spec:
      containers:
        - image: bjoggis/jonasandersen-admin:v0-x86_64
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password