apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-data
  namespace: dashy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi