apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: bjoggis/authorization-server:latest
          ports:
            - containerPort: 8899
