apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: jonasandersen-no
spec:
  selector:
    matchLabels:
      app: authorization
  replicas: 1
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
        - name: authorization
          image: bjoggis/authorization-server:latest
          ports:
            - containerPort: 8899
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
