apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: jonasandersen-no
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: bjoggis/jonasandersen-gateway:v0.0.14
          ports:
            - containerPort: 8080
