apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hearts
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
        autoscaling.knative.dev/window: "30m"
    spec:
      containers:
        - image: bjoggis/hearts:1
          ports:
            - containerPort: 3000
