apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: isegranfasade
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
        autoscaling.knative.dev/window: "10m"
    spec:
      containers:
        - image: theahat/isegranfasade:v0.0.4 # {"$imagepolicy": "flux-system:isegranfasade"}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
