apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: website
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: bjoggis/jonasandersen-no:v0.0.4
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: linode4j
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: bjoggis/linode4j:v0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: username
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: password
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "5m"
    spec:
      containers:
        - image: bjoggis/jonasandersen-gateway:v0.0.7
          ports:
            - containerPort: 8080
