apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: website
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/window: "30s"
    spec:
      imagePullSecrets:
        - name: image-credentials
      containers:
        - image: ghcr.io/notbjoggisatall/jonasandersen-no:v0.0.1
          ports:
            - containerPort: 8080
