apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: website
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: bjoggis/jonasandersen-no:v0.0.4
          ports:
            - containerPort: 8080
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway
  namespace: jonasandersen-no
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/activation-scale: "3"
        autoscaling.knative.dev/max-scale: "100"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "5m"
    spec:
      containers:
        - image: bjoggis/jonasandersen-gateway:v0.0.7
          ports:
            - containerPort: 8080