apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: jonasandersen-website
  namespace: flux-system
spec:
  image: bjoggis/jonasandersen-no
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jonasandersen-website
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jonasandersen-no
  policy:
    semver:
      range: v0.0.x
