---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: jonasandersen-website
  name: jonasandersen-website
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: jonasandersen-website
  name: jonasandersen-website
  namespace: jonasandersen-website
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: jonasandersen-website
  name: gotk-reconciler
  namespace: jonasandersen-website
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:jonasandersen-website:reconciler
  - kind: ServiceAccount
    name: jonasandersen-website
    namespace: jonasandersen-website