apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: website
  namespace: jonasandersen-website
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "2"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: bjoggis/jonasandersen-no:v0.0.8 # {"$imagepolicy": "flux-system:jonasandersen-no"}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-profiles
                  key: spring_profiles_active