apiVersion: apps/v1
kind: Deployment
metadata:
  name: spillhuset-web
  namespace: tobias
spec:
  selector:
    matchLabels:
      app: spillhuset-web
  replicas: 1
  template:
    spec:
      containers:
        - image: bjoggis/spillhuset-web:1
          name: spillhuset-web
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spillhuset-web-service
  namespace: tobias
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: ClusterIP
  selector:
    app: spillhuset-web