apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: config-server
  namespace: bjoggis-com
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/metric: "rps"
        autoscaling.knative.dev/target: "200"
    spec:
      containers:
        - image: bjoggis/config-server:v3.12.2
          ports:
            - containerPort: 8888
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8888
          env:
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: encrypt_key
            - name: SPRING_CLOUD_CONFIG_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: jdbc_url
            - name: SPRING_CLOUD_CONFIG_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: jdbc_username
            - name: SPRING_CLOUD_CONFIG_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: jdbc_password
            - name: SPRING_CLOUD_CONFIG_SECURITY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: security_username
            - name: SPRING_CLOUD_CONFIG_SECURITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-server-credentials
                  key: security_password
