---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: bjoggis-com
  name: bjoggis-com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: bjoggis-com
  name: bjoggis-com
  namespace: bjoggis-com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: bjoggis-com
  name: gotk-reconciler
  namespace: bjoggis-com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:bjoggis-com:reconciler
  - kind: ServiceAccount
    name: bjoggis-com
    namespace: bjoggis-com