apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - rabbitmq-operator.yaml
  - https://github.com/knative-extensions/eventing-rabbitmq/releases/download/knative-v1.12.0/rabbitmq-broker.yaml
