apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: selfhosted-helmcharts
  namespace: flux-system
spec:
  interval: 1m
  url: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: dashy
spec:
  interval: 1m
  timeout: 5m
  chart:
    spec:
      chart: dashy
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: selfhosted-helmcharts
        namespace: flux-system
      interval: 1m
  values:
    static:
      enabled: false
    volumeMounts:
      persistentVolumeClaim:
        claimName: dashy-data
