apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spillhuset-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: knative-serving
  interval: 30s
  path: ./tenants/spillhuset
  prune: true
  retryInterval: 1m
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
