apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
spec:
  nameserver:
    image:
      repo: tailscale/k8s-nameserver
      tag: unstable
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.102.241.19
searchDomains: # optional
  domains:
    - jonasandersen.dev
    - ts.net
  disableDefault: false