apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: 100.119.101.9
  name: five   # service name
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName