apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: five.pancake-vibe.ts.net
  name: five
  namespace: tailscale
spec:
  externalName: placeholder   # any value - will be overwritten by operator
  type: ExternalName