apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 1m
  timeout: 3m
  chart:
    spec:
      chart: tempo
      version: 2.2.3
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: monitoring
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: tempo-bucket
      valuesKey: username
      targetPath: storage.trace.s3.access_key
    - kind: Secret
      name: tempo-bucket
      valuesKey: password
      targetPath: storage.trace.s3.secret_key
  values:
    tempo:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://kube-prometheus-stack-prometheus:9090/api/v1/write"

      # Enable service graphs and span metrics
      overrides:
        defaults:
          metrics_generator:
            processors: [ service-graphs, span-metrics, local-blocks ]

      # Enable persistence for realistic setup
      persistence:
        enabled: false

      storage:
        trace:
          backend: s3
          s3:
            bucket: bucket01
            endpoint: qnas.tailscale.svc.cluster.local:8010
            insecure: true
          wal:
            path: /var/tempo/wal