apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-alloy
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/grafana-alloy
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  timeout: 5m
  wait: true