apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profiles
  namespace: jonasandersen-admin
data:
  spring_profiles_active: "prod, cluster20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profiles
  namespace: thea
data:
  spring_profiles_active: "prod, cluster20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profiles
  namespace: valorant
data:
  spring_profiles_active: "prod, cluster20"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-profiles
  namespace: jonasandersen-website
data:
  spring_profiles_active: "prod, cluster20"