---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: grafana-alloy
data:
  alloy.yaml: |
      logging {
        level = "info"
        format = "logfmt"
    }
        
        prometheus.remote_write "default" {
        endpoint {
        url = "http://your-prometheus-remote-write-endpoint"
        }
    }
        
        prometheus.scrape "node_exporter" {
        targets = [{"__address__" = "node-exporter:9100"}]
        forward_to = [prometheus.remote_write.default.receiver]
    }
