apiVersion: v1
kind: Namespace
metadata:
  name: grafana-alloy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana-alloy
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
