apiVersion: v1
kind: Namespace
metadata:
  name: grafana-alloy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-helm-chart
  namespace: grafana-alloy
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana-helm-chart
        namespace: grafana-alloy
  interval: 1m
  values:
    alloy:
      configMap:
        content: |-
          // Write your Alloy config here:
          logging {
            level = "info"
            format = "logfmt"
          }
          otelcol.receiver.otlp "example" {
            grpc {
              endpoint = "127.0.0.1:4317"
            }

            http {
              endpoint = "127.0.0.1:4318"
            }

            output {
              metrics = [otelcol.processor.batch.example.input]
              logs    = [otelcol.processor.batch.example.input]
              traces  = [otelcol.processor.batch.example.input]
            }
          }